### ISSUE TITLE
'pip' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Phanboy** [Blue9/AudioJack-GUI#23]
Hi,
I'm stuck at the third step, when I enter the command into cmd I get the following error
'pip' is not recognized as an internal or external command'
Thanks

**Comment by Blue9** [comment]
This is because the Python scripts folder is not in your PATH environment variable. Paste the following into Command Prompt or PowerShell (assuming you installed Python 2.7 in the default directory):

    setx PATH "%PATH%;C:\Python27\Scripts"

Restart the command prompt and `pip` should be working.

**Comment by Phanboy** [comment]
Still getting the same error
I've tried adding it to the path under environment variables in advanced system settings

**Comment by Phanboy** [comment]
Thanks, that fixed it but the link for the audiojack icon doesn't seem to be working

**Comment by Blue9** [comment]
Thanks, fixed.

**Comment by Phanboy** [comment]
I finally got the app running, but after entering a youtube link
It reaches 'Extracting video information' before my ram usage spikes from ~2gb to 16gb, and my cpu usage spikes from 5% to 50% causing my whole computer to lag until I close the file

**Comment by Blue9** [comment]
What version of Python are you running? Another user was having a similar issue until they updated Python to version 2.7.13.

**Comment by Phanboy** [comment]
Works fine after installing 2.7.13.
Cheers!
